spring.application.name=fitnesstracker
# The URL of your database (replace 'testdatabase' if yours is named differently)
spring.datasource.url=jdbc:mysql://localhost:3306/fitness_tracker?useSSL=false&serverTimezone=UTC

# Your MySQL credentials
spring.datasource.username=root
spring.datasource.password=BigBoySLooking18@

# The driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Import the .env file from the root project directory
spring.config.import=optional:file:.env[.properties]

# USDA API URL
usda.api.base-url=https://api.nal.usda.gov/fdc/v1
usda.api.key=${usda.api.key}

# API Ninja API Key
api.ninja.key=CRIXppVGzvAOh1CdvoNAbQxgp5BNlMvbttUlgQvZ
api.ninja.base-url=https://api.api-ninjas.com